= nodejs-tester-server
This repository showcases how to create a container image with a Nodejs Hello World.

The code is based on the following repository from the Red Hat Software Collections: https://github.com/sclorg/s2i-nodejs-container/blob/master/12/README.md 


== 1. How to deploy app on OCP 

[source, bash]
----
# Create namespace for the application
oc new-project istio-testing --display-name="Istio Testing"

# Add your namespace to the SMMR
oc apply -f ocp/ServiceMeshMember.yaml

# Create application using s2i
oc new-app nodejs:12~https://github.com/alvarolop/nodejs-tester-server

# Autoinject sidecar using the Istio annotation
oc patch deployment nodejs-tester-server --type='json' -p "[{\"op\": \"add\", \"path\": \"/spec/template/metadata/annotations\", \"value\": {\"sidecar.istio.io/inject\": \"true\"}}]"
----

Now, substitute the configuration of the deployment with the configuration of the file `deployment.yaml`:

* Sidecar annotation.
* Liveness and readiness probes.
* Injecting the variable HOST using the pod name. This is the configuration that breaks the probes.

This is the content that you have to modify:


### Option 1: Invalid configuration 
[source, yaml]
----
          env:
            - name: HOST
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: PORT
              value: '8080'
          readinessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
----

### Option 2: Valid configuration 
[source, yaml]
----
          env:
            - name: PORT
              value: '8080'
          readinessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
----

### Option 3: Invalid configuration using curl command
[source, yaml]
----
          env:
            - name: HOST
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: PORT
              value: '8080'
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - '-c'
                - 'curl http://$HOSTNAME:$PORT'
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - '-c'
                - 'curl http://$HOSTNAME:$PORT'
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
----

////
## 2. How to deploy app on OCP manually

[source, bash]
----
oc new-app nodejs:12~https://github.com/alvarolop/nodejs-tester-server

oc new-app --name=nodejs-fixed-server-A https://github.com/alvarolop/nodejs-tester-server
----

After creating the application, you may need to do the following:

[source, bash]
----
# Include the istio annotation
oc patch deployment nodejs-tester-server --type='json' -p "[{\"op\": \"add\", \"path\": \"/spec/template/metadata/annotations\", \"value\": {\"sidecar.istio.io/inject\": \"true\"}}]"

# Add an environment variable to listen on the pod name.

# Add liveness and readiness probes.
oc set probe deployment/nodejs-tester-server --liveness --get-url= 
----
////

## Annex. How to create image in local

[source, bash]
----
podman build -t node-app .
podman run localhost/node-app
podman run --env PORT=8080 localhost/node-app
----
